version: '3'

services:
  latex:
    build: .
    # restart: always
    command: make start
    ports:
     - "127.0.0.1:2345:8080"
    volumes:
     - ./tmp:/app/latex-on-http/tmp
    environment:
      # SENTRY_DSN: 
      CACHE_HOST: cache
  cache:
    build:
      context: .
      dockerfile: cache.Dockerfile
    # restart: always
    volumes:
     - ./tmp:/app/latex-on-http/tmp
    # environment:
      # SENTRY_DSN: 
