version: '3'

services:
  latex:
    build: .
    command: make debug
    ports:
     - "8080:8080"
    volumes:
     - .:/app/latex-on-http
    environment:
      CACHE_HOST: cache
      # KEEP_WORKSPACE_DIR: 1
      KEEP_WORKSPACE_DIR_ON_ERROR: 1
  cache:
    build:
      context: .
      dockerfile: cache.Dockerfile
    volumes:
     - .:/app/latex-on-http
